SELECT DISTINCT(X.*)
FROM (  
    SELECT 
        EVEE.*
    FROM 
        EVENTS_EVENT AS EVEE
        JOIN HOME_EVENTCATEGORY AS HEC
        ON EVEE.ID = HEC.EVENT_ID
        JOIN HOME_CATEGORY AS HCAT
        ON HCAT.ID = HEC.CATEGORY_ID
        JOIN HOME_LOCATION AS HLC
        ON HLC.ID = EVEE.LOCATION_ID
        JOIN HOME_CITY AS HCITY
        ON HCITY.ID = HLC.CITY_ID
        JOIN HOME_COUNTRY AS HCONT
        ON HCONT.ID = HCITY.COUNTRY_ID
    WHERE 
        {where_cond} EVEE.START_DATE >= CURRENT_DATE
    ORDER BY 
        EVEE.START_DATE
    ) AS X;