# Generated by Django 4.0.4 on 2022-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
