# Generated by Django 4.0.4 on 2022-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_event_id_eventimage_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='main',
        ),
        migrations.AddField(
            model_name='event',
            name='main_image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/b/b1/Missing-image-232x150.png', max_length=1020),
        ),
    ]
