# Generated by Django 4.0.4 on 2022-05-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_url',
            field=models.CharField(default='', max_length=510),
        ),
    ]
