# Generated by Django 4.0.4 on 2022-05-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location_map_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
