# Generated by Django 4.0.4 on 2022-05-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0003_alter_entertainer_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_rename_postal_code_id_ticket_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteEntertainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainers.entertainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
