# Generated by Django 4.0.4 on 2022-05-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userfavoriteentertainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.postalcode'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
