# Generated by Django 4.0.4 on 2022-05-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_city_state_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(default='ISL', max_length=3),
            preserve_default=False,
        ),
    ]
