# Generated by Django 4.0.4 on 2022-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_country_iso3_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
    ]
