# Generated by Django 4.0.4 on 2022-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_ticket_email_alter_ticket_first_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='unique_event_category'),
        ),
        migrations.AddConstraint(
            model_name='evententertainer',
            constraint=models.UniqueConstraint(fields=('event', 'entertainer'), name='unique_event_entertainer'),
        ),
        migrations.AddConstraint(
            model_name='eventtickettypeprice',
            constraint=models.UniqueConstraint(fields=('event', 'ticket_type'), name='unique_event_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='userfavoritecategory',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category'),
        ),
        migrations.AddConstraint(
            model_name='userfavoriteentertainer',
            constraint=models.UniqueConstraint(fields=('user', 'entertainer'), name='unique_user_favorite_entertainer'),
        ),
    ]
