# Generated by Django 4.0.4 on 2022-05-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_eventcategory_unique_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.country'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(default=7777777, max_length=32),
            preserve_default=False,
        ),
    ]
